// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.2
// source: api/flow/v1/flow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlowRequest) Reset() {
	*x = CreateFlowRequest{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowRequest) ProtoMessage() {}

func (x *CreateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowRequest.ProtoReflect.Descriptor instead.
func (*CreateFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{0}
}

type CreateFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlowReply) Reset() {
	*x = CreateFlowReply{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowReply) ProtoMessage() {}

func (x *CreateFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowReply.ProtoReflect.Descriptor instead.
func (*CreateFlowReply) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{1}
}

type UpdateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlowRequest) Reset() {
	*x = UpdateFlowRequest{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowRequest) ProtoMessage() {}

func (x *UpdateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{2}
}

type UpdateFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlowReply) Reset() {
	*x = UpdateFlowReply{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowReply) ProtoMessage() {}

func (x *UpdateFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowReply.ProtoReflect.Descriptor instead.
func (*UpdateFlowReply) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{3}
}

type DeleteFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlowRequest) Reset() {
	*x = DeleteFlowRequest{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlowRequest) ProtoMessage() {}

func (x *DeleteFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlowRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{4}
}

type DeleteFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlowReply) Reset() {
	*x = DeleteFlowReply{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlowReply) ProtoMessage() {}

func (x *DeleteFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlowReply.ProtoReflect.Descriptor instead.
func (*DeleteFlowReply) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{5}
}

type GetFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowRequest) Reset() {
	*x = GetFlowRequest{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowRequest) ProtoMessage() {}

func (x *GetFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowRequest.ProtoReflect.Descriptor instead.
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{6}
}

type GetFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowReply) Reset() {
	*x = GetFlowReply{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowReply) ProtoMessage() {}

func (x *GetFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowReply.ProtoReflect.Descriptor instead.
func (*GetFlowReply) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{7}
}

type ListFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowRequest) Reset() {
	*x = ListFlowRequest{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowRequest) ProtoMessage() {}

func (x *ListFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowRequest.ProtoReflect.Descriptor instead.
func (*ListFlowRequest) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{8}
}

type ListFlowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowReply) Reset() {
	*x = ListFlowReply{}
	mi := &file_api_flow_v1_flow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowReply) ProtoMessage() {}

func (x *ListFlowReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_flow_v1_flow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowReply.ProtoReflect.Descriptor instead.
func (*ListFlowReply) Descriptor() ([]byte, []int) {
	return file_api_flow_v1_flow_proto_rawDescGZIP(), []int{9}
}

var File_api_flow_v1_flow_proto protoreflect.FileDescriptor

const file_api_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x16api/flow/v1/flow.proto\x12\vapi.flow.v1\"\x13\n" +
	"\x11CreateFlowRequest\"\x11\n" +
	"\x0fCreateFlowReply\"\x13\n" +
	"\x11UpdateFlowRequest\"\x11\n" +
	"\x0fUpdateFlowReply\"\x13\n" +
	"\x11DeleteFlowRequest\"\x11\n" +
	"\x0fDeleteFlowReply\"\x10\n" +
	"\x0eGetFlowRequest\"\x0e\n" +
	"\fGetFlowReply\"\x11\n" +
	"\x0fListFlowRequest\"\x0f\n" +
	"\rListFlowReply2\xf3\x02\n" +
	"\x04Flow\x12J\n" +
	"\n" +
	"CreateFlow\x12\x1e.api.flow.v1.CreateFlowRequest\x1a\x1c.api.flow.v1.CreateFlowReply\x12J\n" +
	"\n" +
	"UpdateFlow\x12\x1e.api.flow.v1.UpdateFlowRequest\x1a\x1c.api.flow.v1.UpdateFlowReply\x12J\n" +
	"\n" +
	"DeleteFlow\x12\x1e.api.flow.v1.DeleteFlowRequest\x1a\x1c.api.flow.v1.DeleteFlowReply\x12A\n" +
	"\aGetFlow\x12\x1b.api.flow.v1.GetFlowRequest\x1a\x19.api.flow.v1.GetFlowReply\x12D\n" +
	"\bListFlow\x12\x1c.api.flow.v1.ListFlowRequest\x1a\x1a.api.flow.v1.ListFlowReplyB$\n" +
	"\vapi.flow.v1P\x01Z\x13flow/api/flow/v1;v1b\x06proto3"

var (
	file_api_flow_v1_flow_proto_rawDescOnce sync.Once
	file_api_flow_v1_flow_proto_rawDescData []byte
)

func file_api_flow_v1_flow_proto_rawDescGZIP() []byte {
	file_api_flow_v1_flow_proto_rawDescOnce.Do(func() {
		file_api_flow_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_flow_v1_flow_proto_rawDesc), len(file_api_flow_v1_flow_proto_rawDesc)))
	})
	return file_api_flow_v1_flow_proto_rawDescData
}

var file_api_flow_v1_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_flow_v1_flow_proto_goTypes = []any{
	(*CreateFlowRequest)(nil), // 0: api.flow.v1.CreateFlowRequest
	(*CreateFlowReply)(nil),   // 1: api.flow.v1.CreateFlowReply
	(*UpdateFlowRequest)(nil), // 2: api.flow.v1.UpdateFlowRequest
	(*UpdateFlowReply)(nil),   // 3: api.flow.v1.UpdateFlowReply
	(*DeleteFlowRequest)(nil), // 4: api.flow.v1.DeleteFlowRequest
	(*DeleteFlowReply)(nil),   // 5: api.flow.v1.DeleteFlowReply
	(*GetFlowRequest)(nil),    // 6: api.flow.v1.GetFlowRequest
	(*GetFlowReply)(nil),      // 7: api.flow.v1.GetFlowReply
	(*ListFlowRequest)(nil),   // 8: api.flow.v1.ListFlowRequest
	(*ListFlowReply)(nil),     // 9: api.flow.v1.ListFlowReply
}
var file_api_flow_v1_flow_proto_depIdxs = []int32{
	0, // 0: api.flow.v1.Flow.CreateFlow:input_type -> api.flow.v1.CreateFlowRequest
	2, // 1: api.flow.v1.Flow.UpdateFlow:input_type -> api.flow.v1.UpdateFlowRequest
	4, // 2: api.flow.v1.Flow.DeleteFlow:input_type -> api.flow.v1.DeleteFlowRequest
	6, // 3: api.flow.v1.Flow.GetFlow:input_type -> api.flow.v1.GetFlowRequest
	8, // 4: api.flow.v1.Flow.ListFlow:input_type -> api.flow.v1.ListFlowRequest
	1, // 5: api.flow.v1.Flow.CreateFlow:output_type -> api.flow.v1.CreateFlowReply
	3, // 6: api.flow.v1.Flow.UpdateFlow:output_type -> api.flow.v1.UpdateFlowReply
	5, // 7: api.flow.v1.Flow.DeleteFlow:output_type -> api.flow.v1.DeleteFlowReply
	7, // 8: api.flow.v1.Flow.GetFlow:output_type -> api.flow.v1.GetFlowReply
	9, // 9: api.flow.v1.Flow.ListFlow:output_type -> api.flow.v1.ListFlowReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_flow_v1_flow_proto_init() }
func file_api_flow_v1_flow_proto_init() {
	if File_api_flow_v1_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_flow_v1_flow_proto_rawDesc), len(file_api_flow_v1_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_api_flow_v1_flow_proto_depIdxs,
		MessageInfos:      file_api_flow_v1_flow_proto_msgTypes,
	}.Build()
	File_api_flow_v1_flow_proto = out.File
	file_api_flow_v1_flow_proto_goTypes = nil
	file_api_flow_v1_flow_proto_depIdxs = nil
}
